language: go
before_install:
  - go get github.com/mitchellh/gox
before_script:
  - gox -os="darwin linux windows" -arch="386 amd64" -build-toolchain
script:
  - gox -os="darwin linux windows" -arch="386 amd64" ./cmd/karn
deploy:
  provider: releases
  api_key:
    secure: WIp4RiewOScnmYsD8GBrxcT+9BTFmABhk2SQvO7gpddPWgXFsaRl8+CQ/6BKxuE+XIj6VA+zhvnWXZ+SDSPaSNbjTbFSfo81AikWobvxLL2+tzwVuYXsd0sfjwHZIQ4cy43NCQn9ZmCd919CNlULneOtWRj+d2khXKuefZqsSn8=
  file:
    - "karn_darwin_386"
    - "karn_darwin_amd64"
    - "karn_linux_386"
    - "karn_linux_amd64"
    - "karn_windows_386.exe"
    - "karn_windows_amd64.exe"
  skip_cleanup: true
  on:
    tags: true
